---
title: "HOMEWORK THREE"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
隨堂練習*

1. 香港搖滾樂隊 Beyond 於 1983 年成立，我們假設成立日期是 1983-12-31，請將成立日期指派給
beyond_start 並轉換成整數輸出在命令列



1. 請以系統日期計算今年是 Beyond 成立幾週年紀念？



1. 1999 年 9 月 21 日 1 時 47 分 16 秒發生震央位於南投縣集集鎮，芮規模 7.3 的地震，請以文字記錄
這個時間，並將它指派給 majorquaketime



1. 1999 年 9 月21 日 1 時 57 分 15 秒發生第一個芮氏規模超過 6 的餘震，請以文字記錄這個時間，並將
它指派給 firstaftershocktime



1. 請將前兩題的???成的變數轉換為時間類型，計算間隔多久發生第一個芮氏規模超過 6 的餘震



```{r}

beyond_start <- as.Date("1983-12-31")
as.integer(beyond_start)

beyond_start <- as.Date("1983-12-31")
days_diff <- Sys.Date() - beyond_start # 計算天數差距
years_diff <- days_diff / 365 # 除以 365 換算成年
years_diff

major_quake_time <- "1999-9-21 01:47:16"

first_aftershock_time <- "1999-9-21 01:57:15"

major_quake_time <- as.POSIXct("1999-9-21 01:47:16")
first_aftershock_time <- as.POSIXct("1999-9-21 01:57:15")
first_aftershock_time - major_quake_time






```

